title: Rom&ko Projects
author: H. Reed Romanko
email: hromanko@bu.edu
description: > # this means to ignore newlines until "baseurl:"
  Space for all of the components of my projects, be it the finished product, data, or useful scripts. There should be stuff here shortly.

# social links
linkedin_username: Reed Romanko # DO NOT include the @ character, or else the build will fail!
github_username:  ReedRomanko # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
